[package]
edition = "2021"
name = "tricked-bot"
version = "1.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
futures = "0.3.21"
log = "0.4.17"
openssl = {version = "0.10.40", features = ["vendored"]}
rand = {version = "0.8.5", features = ["log", "serde"]}
reqwest = {version = "0.11", features = ["json"]}
rusqlite = "0.27.0"
serde = {version = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"
tokio = {version = "1.18.2", features = ["rt", 'macros']}
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
twilight-bucket = "0.2.1"
twilight-cache-inmemory = "0.10.2"
twilight-gateway = {version = "0.10.1", features = [
  "simd-json",
  "native",
  "zlib-simd",
  "tracing",
]}
twilight-http = {version = "0.10.2", features = [
  "simd-json",
  "trust-dns",
  "native",
]}
twilight-model = "0.10.2"
