[package]
authors = ["Tricked-dev"]
description = "A simple discord bot made for my [discord](https://discord.gg/mY8zTARu4g)"
edition = "2021"
license = "Apache-2"
name = "tricked-bot"
version = "1.3.0"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []

[dependencies]
argh = "0.1.7"
bytes = "1.1.0"
futures = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.17"
openssl = { version = "0.10.40", features = ["vendored"] }
rand = { version = "0.8.5", features = ["log", "serde"] }
reqwest = { version = "0.11.10", features = ["json"] }
rusqlite = "0.27.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.18.2", features = ["rt", "rt-multi-thread", 'macros'] }
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
twilight-bucket = "0.2.2"
twilight-cache-inmemory = "0.11"
twilight-embed-builder = "0.11"
twilight-gateway = { version = "0.11.0", features = ["native"] }
twilight-http = { version = "0.11.0", features = ["native"] }
twilight-model = "0.11.0"
urlencoding = "2.1.0"
zephyrus = "0.2.9"
clap = { version = "4.0.29", features = ["derive", "cargo", "env"] }
base64 = "0.13.1"
