[package]
authors = ["Tricked-dev"]
description = "A simple discord bot made for my [discord](https://discord.gg/mY8zTARu4g)"
edition = "2021"
license = "Apache-2"
name = "tricked-bot"
version = "1.3.0"

[profile.release]
lto = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
anyhow = "1.0.57"
argh = "0.1.7"
bytes = "1.1.0"
chrono = "0.4.19"
feed-rs = "1.0.0"
futures = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.17"
mdcat = {version = "0.27.1", git = "https://codeberg.org/tricked/mdcat", rev = "e966d5e5f678616b0010e315515af276d5edb091"}
openssl = { version = "0.10.40", features = ["vendored"] }
pulldown-cmark = "0.9.1"
qrcodegen = "1.8.0"
rand = { version = "0.8.5", features = ["log", "serde"] }
reqwest = { version = "0.11.10", features = ["json"] }
rhtml2md = "0.0.1"
rusqlite = "0.27.0"
select = "0.5.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
syntect = "5.0.0"
tokio = { version = "1.18.2", features = ["rt", "rt-multi-thread", 'macros'] }
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
twilight-bucket = "0.2.2"
twilight-cache-inmemory = "0.11"
twilight-embed-builder = "0.11"
twilight-gateway = { version = "0.11.0", features = [
  "native",
  "zlib-simd",
] }
twilight-http = { version = "0.11.0", features = [
  "native",
] }
twilight-model = "0.11.0"
urlencoding = "2.1.0"
zephyrus = "0.2.9"
zip = "0.6.2"
lingua = { version = "1.4.0", default-features = false, features = ["polish", "english"] }
