[package]
edition = "2021"
name = "tricked-bot"
version = "1.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
bytes = "1.1.0"
futures = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.17"
mdcat = {version = "0.27.1", git = "https://codeberg.org/tricked/mdcat"}
openssl = {version = "0.10.40", features = ["vendored"]}
pulldown-cmark = "0.9.1"
qrcodegen = "1.8.0"
rand = {version = "0.8.5", features = ["log", "serde"]}
reqwest = {version = "0.11", features = ["json"]}
rusqlite = "0.27.0"
serde = {version = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"
syntect = "4.6"
tokio = {version = "1.18.2", features = ["rt", "rt-multi-thread", 'macros']}
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
twilight-bucket = "0.2.1"
twilight-embed-builder = "0.10.1"
twilight-gateway = {version = "0.10.1", features = [
  "native",
  "zlib-simd",
  "tracing",
]}
twilight-http = {version = "0.10.2", features = [
  "native",
]}
twilight-model = "0.10.2"
zip = "0.6.2"
