[L]
message = "+ ratio"
[F]
react = "🇫"
[DN]
message = "Digital Native"
[GN]
message = "https://www.youtube.com/watch?v=ykLDTsfnE5A"
[SKULL]
react = "💀"
[RUST]
react = "🦀"
[JAVA]
react = "🤮"
[CLOWN]
message= "You are a clown"
[BALLS]
message="https://www.reddit.com/r/WTF/comments/wqibrw/this_hurts_like_hell/"